name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
      REGION: ${{ secrets.GCP_REGION }}
      IMAGE: northamerica-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfolio-website/portfolio:${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev --quiet

    - name: Build Container image
      run: |
        docker build -t $IMAGE .

    - name: Push Docker image
      run: |
        docker push $IMAGE

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ secrets.CLOUD_RUN_SERVICE }}
        image: $IMAGE
        region: ${{ secrets.GCP_REGION }}
        allow-unauthenticated: true
